### PR TITLE
added proxies kwarg

### PR DESCRIPTION
**Pull request by stijnvanlooy**
small changes mentioned in #58

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@stijnvanlooy thanks! I'm trying to get https://github.com/fluves/pywaterinfo/pull/60 (with some fixes on the CI setup) passed (when token granted by VMM works again) so the unit testing can be applied on this PR as well.

**Comment by stijnvanhoey** [comment]
@stijnvanlooy  I wanted to update your PR with the adjustments on the CI setup, but I'm not able to add additional commits to your PR.  Could you check the box in the pull request that says “Allow edits from maintainers.”?

**Comment by stijnvanlooy** [comment]
@stijnvanhoey the box is checked
it was already, so I applied the good old turning it off and on again ;) Hope you are able to add commits now

**Comment by stijnvanhoey** [comment]
@stijnvanlooy thanks for the PR. I had to adjust some settings of the CI and we bumped into some API issues on the hic/vmm side, but all is fine now.

**Pull request merged**
